/**
 * Collection locale — textes courts, domaine public ou originaux.
 * attributionConfidence:
 *   verified — attribution documentée de façon fiable
 *   traditional — formule proverbiale, origine souvent floue
 *   uncertain — origine ou auteur incertain
 *   original — créé pour cette application
 */

export const PHRASES = [
  {
    id: 'fr-rest-001',
    textOriginal: 'Tu n’as pas à tout faire aujourd’hui. Une petite chose suffit parfois.',
    language: 'Français',
    frenchTranslation: null,
    category: 'repos',
    tone: 'apaisant',
    attributionConfidence: 'original',
    source: 'Horizon — collection locale',
  },
  {
    id: 'en-per-001',
    textOriginal: 'It does not matter how slowly you go as long as you do not stop.',
    language: 'Anglais',
    frenchTranslation: 'Peu importe la lenteur, tant que tu ne t’arrêtes pas.',
    region: 'Royaume-Uni (contexte historique)',
    author: 'Confucius',
    category: 'persévérance',
    tone: 'inspirant',
    attributionConfidence: 'traditional',
    source: 'Attribué à Confucius ; traduction libre',
  },
  {
    id: 'es-hum-001',
    textOriginal: 'No hay mal que por bien no venga.',
    language: 'Espagnol',
    frenchTranslation: 'Il n’y a pas de mal sans quelque bien.',
    region: 'Espagne / tradition hispanophone',
    category: 'réconfort',
    tone: 'inspirant',
    attributionConfidence: 'traditional',
    source: 'Proverbe espagnol ; traduction libre',
  },
  {
    id: 'de-mot-001',
    textOriginal: 'Der Weg ist das Ziel.',
    language: 'Allemand',
    frenchTranslation: 'Le chemin est le but.',
    region: 'Allemagne',
    author: 'Konfuzius (attribution populaire)',
    category: 'motivation',
    tone: 'inspirant',
    attributionConfidence: 'uncertain',
    source: 'Formule souvent citée ; lien exact avec Konfuzius incertain',
  },
  {
    id: 'jp-cal-001',
    textOriginal: '七転び八起き',
    language: 'Japonais',
    frenchTranslation: 'Tomber sept fois, se relever huit.',
    region: 'Japon',
    category: 'persévérance',
    tone: 'inspirant',
    attributionConfidence: 'traditional',
    source: 'Proverbe japonais (nanakorobi yaoki) ; traduction libre',
  },
  {
    id: 'ar-pea-001',
    textOriginal: 'الصبر مفتاح الفرج',
    language: 'Arabe',
    frenchTranslation: 'La patience est la clé du soulagement.',
    region: 'Monde arabe (proverbe répandu)',
    category: 'persévérance',
    tone: 'apaisant',
    attributionConfidence: 'traditional',
    source: 'Proverbe arabe ; translittération et traduction libres',
  },
  {
    id: 'pt-joy-001',
    textOriginal: 'Devagar também se chega lá.',
    language: 'Portugais',
    frenchTranslation: 'Lentement, on arrive aussi.',
    region: 'Portugal / Brésil',
    category: 'persévérance',
    tone: 'réconfort',
    attributionConfidence: 'traditional',
    source: 'Expression populaire lusophone ; traduction libre',
  },
  {
    id: 'sw-mot-001',
    textOriginal: 'Haraka haraka haina baraka.',
    language: 'Swahili',
    frenchTranslation: 'Trop vite, sans bénédiction. (La précipitation n’apporte pas le bonheur.)',
    region: 'Afrique de l’Est',
    category: 'repos',
    tone: 'apaisant',
    attributionConfidence: 'traditional',
    source: 'Proverbe swahili ; traduction libre',
  },
  {
    id: 'en-hum-001',
    textOriginal: 'I am an early bird and a night owl. So I am wise and tired.',
    language: 'Anglais',
    frenchTranslation: 'Je suis lève-tôt et oiseau de nuit. Donc je suis sage et fatigué.',
    author: 'Liza Palmer',
    category: 'humour',
    tone: 'drôle',
    attributionConfidence: 'verified',
    source: 'Citation attribuée à l’autrice Liza Palmer ; traduction libre',
  },
  {
    id: 'fr-cre-001',
    textOriginal: 'Une idée imparfaite vaut mieux qu’un carnet vide.',
    language: 'Français',
    frenchTranslation: null,
    category: 'créativité',
    tone: 'inspirant',
    attributionConfidence: 'original',
    source: 'Horizon — collection locale',
  },
  {
    id: 'it-mot-001',
    textOriginal: 'Chi va piano, va sano e va lontano.',
    language: 'Italien',
    frenchTranslation: 'Qui va doucement va sainement et va loin.',
    region: 'Italie',
    category: 'persévérance',
    tone: 'apaisant',
    attributionConfidence: 'traditional',
    source: 'Proverbe italien ; traduction libre',
  },
  {
    id: 'pl-res-001',
    textOriginal: 'Gdzie kucharek sześć, tam nie ma co jeść.',
    language: 'Polonais',
    frenchTranslation: 'Quand il y a trop de cuisinières, on ne mange pas. (Trop d’avis peuvent paralyser.)',
    region: 'Pologne',
    category: 'humour',
    tone: 'drôle',
    attributionConfidence: 'traditional',
    source: 'Proverbe polonais ; traduction libre',
  },
  {
    id: 'en-insp-001',
    textOriginal: 'You are allowed to be both a masterpiece and a work in progress.',
    language: 'Anglais',
    frenchTranslation: 'Tu as le droit d’être à la fois une œuvre aboutie et un chantier en cours.',
    author: 'Sophia Bush',
    category: 'réconfort',
    tone: 'inspirant',
    attributionConfidence: 'verified',
    source: 'Citation attribuée à Sophia Bush ; traduction libre',
  },
  {
    id: 'zh-cal-001',
    textOriginal: '千里之行，始于足下',
    language: 'Chinois (mandarin)',
    frenchTranslation: 'Un voyage de mille li commence par un pas.',
    region: 'Chine',
    author: 'Laozi',
    category: 'persévérance',
    tone: 'inspirant',
    attributionConfidence: 'traditional',
    source: 'Dao De Jing, ch. 64 ; traduction libre',
  },
  {
    id: 'ko-rest-001',
    textOriginal: '시작이 반이다',
    language: 'Coréen',
    frenchTranslation: 'Commencer, c’est déjà la moitié du chemin.',
    region: 'Corée',
    category: 'motivation',
    tone: 'inspirant',
    attributionConfidence: 'traditional',
    source: 'Expression coréenne courante ; traduction libre',
  },
  {
    id: 'en-sci-001',
    textOriginal: 'Life is like riding a bicycle. To keep your balance, you must keep moving.',
    language: 'Anglais',
    frenchTranslation: 'La vie est comme un vélo : pour garder l’équilibre, il faut avancer.',
    author: 'Albert Einstein',
    category: 'motivation',
    tone: 'inspirant',
    attributionConfidence: 'verified',
    source: 'Lettre à son fils Eduard, 1930 ; traduction libre',
  },
  {
    id: 'fr-hum-001',
    textOriginal: 'Si tu ne peux pas tout faire, fais au moins une chose en pyjama avec dignité.',
    language: 'Français',
    frenchTranslation: null,
    category: 'humour',
    tone: 'drôle',
    attributionConfidence: 'original',
    source: 'Horizon — collection locale',
  },
  {
    id: 'hi-pea-001',
    textOriginal: 'धीरे-धीरे रे मना, धीरे सब कुछ होता है',
    language: 'Hindi',
    frenchTranslation: 'Doucement, ô esprit : doucement, tout se fait.',
    region: 'Inde',
    author: 'Kabir',
    category: 'repos',
    tone: 'apaisant',
    attributionConfidence: 'traditional',
    source: 'Poésie de Kabir (tradition) ; traduction libre',
  },
  {
    id: 'en-unc-001',
    textOriginal: 'This too shall pass.',
    language: 'Anglais',
    frenchTranslation: 'Cela aussi passera.',
    category: 'réconfort',
    tone: 'apaisant',
    attributionConfidence: 'uncertain',
    source: 'Formule ancienne, origine débattue (persan, soufie, etc.) ; traduction libre',
  },
  {
    id: 'yo-wis-001',
    textOriginal: 'Ìwà pẹ̀lẹ́ kì í ṣe òde.',
    language: 'Yoruba',
    frenchTranslation: 'La douceur n’est pas de la faiblesse.',
    region: 'Nigeria / Bénin',
    category: 'réconfort',
    tone: 'inspirant',
    attributionConfidence: 'traditional',
    source: 'Proverbe yoruba ; translittération et traduction libres',
  },
  {
    id: 'nl-hum-001',
    textOriginal: 'Alles is leuker met koffie. Behalve inslapen.',
    language: 'Néerlandais',
    frenchTranslation: 'Tout est plus sympa avec du café. Sauf s’endormir.',
    region: 'Pays-Bas',
    category: 'humour',
    tone: 'drôle',
    attributionConfidence: 'original',
    source: 'Horizon — collection locale (ton néerlandais)',
  },
  {
    id: 'en-rest-002',
    textOriginal: 'Rest is not a reward. It is a requirement.',
    language: 'Anglais',
    frenchTranslation: 'Le repos n’est pas une récompense. C’est un besoin.',
    category: 'repos',
    tone: 'apaisant',
    attributionConfidence: 'original',
    source: 'Horizon — collection locale',
  },
  {
    id: 'tr-mot-001',
    textOriginal: 'Damlaya damlaya göl olur.',
    language: 'Turc',
    frenchTranslation: 'Goutte à goutte, on fait un lac.',
    region: 'Turquie',
    category: 'persévérance',
    tone: 'inspirant',
    attributionConfidence: 'traditional',
    source: 'Proverbe turc ; traduction libre',
  },
  {
    id: 'fr-mot-002',
    textOriginal: 'Ton rythme est valable, même s’il ne ressemble à aucun autre.',
    language: 'Français',
    frenchTranslation: null,
    category: 'réconfort',
    tone: 'apaisant',
    attributionConfidence: 'original',
    source: 'Horizon — collection locale',
  },
];

export const CATEGORY_LABELS = {
  motivation: 'Motivation',
  humour: 'Humour',
  persévérance: 'Persévérance',
  créativité: 'Créativité',
  repos: 'Repos',
  réconfort: 'Réconfort',
};
